(()=>{var e={};e.id=661,e.ids=[661],e.modules={846:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},3033:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-unit-async-storage.external.js")},3295:e=>{"use strict";e.exports=require("next/dist/server/app-render/after-task-async-storage.external.js")},4132:(e,t,r)=>{"use strict";r.a(e,async(e,s)=>{try{r.r(t),r.d(t,{POST:()=>o});var a=r(2190),i=r(4939),n=e([i]);let c=new(i=(n.then?(await n)():n)[0]).Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:!1}});async function o(e){try{let{name:t,phone:r,email:s,status:i,interest:n,ticketId:o}=await e.json(),u=await c.connect();await u.query(`
      CREATE TABLE IF NOT EXISTS registrations (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        phone VARCHAR(50) NOT NULL,
        email VARCHAR(255) NOT NULL,
        status VARCHAR(100),
        interest VARCHAR(255),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ticket_downloaded BOOLEAN DEFAULT FALSE,
        ticket_id VARCHAR(50)
      )
    `);try{await u.query("ALTER TABLE registrations ADD COLUMN ticket_downloaded BOOLEAN DEFAULT FALSE")}catch(e){}try{await u.query("ALTER TABLE registrations ADD COLUMN ticket_id VARCHAR(50)")}catch(e){}let p=await u.query("INSERT INTO registrations (name, phone, email, status, interest, ticket_id) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id",[t,r,s,i,n,o]);return u.release(),a.NextResponse.json({success:!0,id:p.rows[0].id},{status:200})}catch(e){return console.error("Registration error:",e),a.NextResponse.json({error:"Internal Server Error"},{status:500})}}s()}catch(e){s(e)}})},4870:e=>{"use strict";e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4939:e=>{"use strict";e.exports=import("pg")},6487:()=>{},8335:()=>{},9294:e=>{"use strict";e.exports=require("next/dist/server/app-render/work-async-storage.external.js")},9472:(e,t,r)=>{"use strict";r.a(e,async(e,s)=>{try{r.r(t),r.d(t,{patchFetch:()=>u,routeModule:()=>p,serverHooks:()=>R,workAsyncStorage:()=>A,workUnitAsyncStorage:()=>d});var a=r(6559),i=r(8088),n=r(7719),o=r(4132),c=e([o]);o=(c.then?(await c)():c)[0];let p=new a.AppRouteRouteModule({definition:{kind:i.RouteKind.APP_ROUTE,page:"/api/register/route",pathname:"/api/register",filename:"route",bundlePath:"app/api/register/route"},resolvedPagePath:"C:\\Users\\MOHAMMED THALHA A\\OneDrive\\Desktop\\Promotional Page\\app\\api\\register\\route.js",nextConfigOutput:"",userland:o}),{workAsyncStorage:A,workUnitAsyncStorage:d,serverHooks:R}=p;function u(){return(0,n.patchFetch)({workAsyncStorage:A,workUnitAsyncStorage:d})}s()}catch(e){s(e)}})}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[447,580],()=>r(9472));module.exports=s})();